[build]
  command = "npm run build"
  publish = "dist"

# API proxy FIRST
[[redirects]]
  from = "/api/contact"
  to = "https://formspree.io/f/xblkvnzg"
  status = 200
  force = true

# SPA rewrite SECOND
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
